name: Docker Push

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  docker-build-action:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set release tag as current date
        id: tag
        run: echo "RELEASE_TAG=v$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          pull: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ env.RELEASE_TAG }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      -   name: Clean old image versions
          uses: quartx-analytics/ghcr-cleaner@v1
          with:
            owner-type: org
            token: ${{ secrets.GITHUB_TOKEN }}
            repository_owner: ${{ github.repository_owner }}
            repository-name: ${{ github.repository }}
            delete-untagged: false
            keep-at-most: 10
